select * from customer limit 20;

--1. What is the total revenue generated by male vs. femail customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2. Which cu
select customer_id, purchase_amount 
from customer
where discount_applied= 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
